apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
  namespace: marketplace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
      - name: orders
        image: farrasjay/orders:latest
        ports:
        - containerPort: 8000
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: DB_PORT
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          value: aaw-marketplace-orders
        - name: VERIFY_TOKEN_API_URL
          value: "http://authentication:8000/api/auth/verify-token"

---
apiVersion: v1
kind: Service
metadata:
  name: orders
  namespace: marketplace
spec:
  selector:
    app: orders
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30001
  type: NodePort