apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: marketplace
type: Opaque
data:
  DB_USER: cG9zdGdyZXM=   # base64 encoded "postgres"
  DB_PASSWORD: cG9zdGdyZXM=  # base64 encoded "postgres"

---
apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
  namespace: marketplace
type: Opaque
data:
  JWT_SECRET: YXV0aF9tc19qd3Rfc2VjcmV0  # base64 encoded "auth_ms_jwt_secret"
  ADMIN_JWT_SECRET: YWRtaW5fYXV0aF9tc19qd3Rfc2VjcmV0  # base64 encoded "admin_auth_ms_jwt_secret"