apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: marketplace
type: Opaque
data:
  DB_USER: postgres  # Base64 = " cG9zdGdyZXM= "
  DB_PASSWORD: postgres  # Base64 = " cG9zdGdyZXM= "

---
apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
  namespace: marketplace
type: Opaque
data:
  JWT_SECRET: auth_ms_jwt_secret  # base64 encoded = YXV0aF9tc19qd3Rfc2VjcmV0
  ADMIN_JWT_SECRET: admin_auth_ms_jwt_secret  # base64 encoded = YWRtaW5fYXV0aF9tc19qd3Rfc2VjcmV0