apiVersion: apps/v1
kind: Deployment
metadata:
  name: products
  namespace: marketplace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products
  template:
    metadata:
      labels:
        app: products
    spec:
      containers:
      - name: products
        image: farrasjay/products:latest
        ports:
        - containerPort: 8000
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: DB_PORT
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          value: aaw-marketplace-products
        - name: VERIFY_TOKEN_API_URL
          value: "http://authentication:8000/api/auth/verify-token"
        - name: GET_TENANT_API_URL
          value: "http://tenant:8000/api/tenant/"

---
apiVersion: v1
kind: Service
metadata:
  name: products
  namespace: marketplace
spec:
  selector:
    app: products
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30002
  type: NodePort