apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication
  namespace: marketplace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication
  template:
    metadata:
      labels:
        app: authentication
    spec:
      containers:
      - name: authentication
        image: farrasjay/authentication:latest
        ports:
        - containerPort: 8000
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: DB_PORT
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          value: aaw-marketplace-authentication
        - name: TENANT_ID
          value: "47dd6b24-0b23-46b0-a662-776158d089ba"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: auth-secret
              key: JWT_SECRET
        - name: ADMIN_JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: auth-secret
              key: ADMIN_JWT_SECRET
        - name: ADMIN_TENANT_ID
          value: "47dd6b24-0b23-46b0-a662-776158d089ba"

---
apiVersion: v1
kind: Service
metadata:
  name: authentication
  namespace: marketplace
spec:
  selector:
    app: authentication
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30000
  type: NodePort